### ISSUE TITLE
Wrong color for ProPhoto color space

### ISSUE THREAD

**Issue by zbutfly** [Kalpanika/x3f#113]
I took x3f by Sigma DP2 Merrill with color space setting of ProPhoto to reserve as much color information as possible. The raw can be processed correctly in Sigma Photo Pro (version 5.x or 6.x) but x3f_extractor produces dng/tif with wrong color. Looks like negative color.

If need, I can provide some samples.

**Comment by rolkar** [comment]
The choice of color space do not affect the data stored in the RAW file or the DNG file, so there is no need for using ProPhoto in order to get more color informationm when using DNG. And ... the TIFF version is not considered useful.

Of course, it should not behave strange if you do.

We have very little support today. But, I can ask Erik if he remembers anything regarding support of color spaces.

BTW - when you say that the DNG looks wrong, what viewer do you use?

**Comment by zbutfly** [comment]
You are right. The x3f is converted into dng with wrong embed thunmnail but correct raw data. On open in LR/PS the image data looks well. 
Of course if directly convert from x3f into tiff, the image color overflow. 
It should cause by the diff (larger) area of ProPhoto than sRGB. But SPP can generate tiff of prophoto. I think it is a possible work can be applied on x3f tools in future.
Thanks for your work and reply.

**Comment by zbutfly** [comment]
supplementary: exif of dng is not copied from x3f. I copy it by exiftool myself.
