### ISSUE TITLE
Possibility to turn off color corrections

### ISSUE THREAD

**Issue by rolkar** [Kalpanika/x3f#51]
It might be useful, for comparisons, to be able to turn off color corrections.

e.g. -no-corrections

**Comment by rolkar** [comment]
I changed this issue to important, because it is hard to fix our color hue issues (#6) without being able to do it.

**Comment by rolkar** [comment]
I assume that the two changes to be made are

(1) x3f_output_dng.c - do not call write_spatial_gain()

(2) x3f_process.c:convert_data() - change the formula for input[color] after /* Get the data */

**Comment by rolkar** [comment]
Another thing to think about. Shall the flag to turn off/on spatial_gain be sent around or a global variable? Or shall we add a struct with flags, a.la. Win32?

**Comment by erikrk** [comment]
On jue, 2015-07-30 at 08:22 -0700, Roland Karlsson wrote:
> I assume that the two changes to be made are
> 
> (1) x3f_output_dng.c - do not call write_spatial_gain()
> 

Correct.

> (2) x3f_process.c:convert_data() - change the formula for input[color]
> after /* Get the data */
> 

Correct. If you don't want to introduce a conditional in the formula
itself, you could just set sgain_num to 0. x3f_calc_spatial_gain will
return 1.0 when sgain_num is 0.

**Comment by erikrk** [comment]
Tough question. Currently, most parameters are passed around as
individual arguments to functions. This makes it quite tedious to add
parameters. It is also possible to reach a limit where the argument
lists start to be a bit long, and it becomes more and more difficult to
remember the order of the arguments.

Some parameters are instead put in in global variables. This makes it a
lot easier to add parameters, but it's kind of ugly. It also introduces
some limitations when it comes to threading. This has no practical
implications currently though.

Since this is essentially a debugging aid, I would suggest using a
global variable, unless you are very keen on introducing a parameter
struct.

**Comment by erikrk** [comment]
Has been fixed. #66
