### ISSUE TITLE
Describe how to set up cross compiler for Windows

### ISSUE THREAD

**Issue by rolkar** [Kalpanika/x3f#55]

**Comment by rolkar** [comment]
Already described in the Vagrantfile

sudo apt-get install mingw-w64

**Comment by mmroden** [comment]
Is that all that's necessary?  Because trying to compile the windows
distribution gives me:

make TARGET=windows-x86_64 dist

make[1]: Entering directory `/vagrant'

make -C src dist

make[2]: Entering directory `/vagrant/src'

rm -f ../dist/x3f_tools-4ec89fa-windows-x86_64.zip

cd ../dist && zip /vagrant/dist/x3f_tools-4ec89fa-windows-x86_64.zip
x3f_tools-4ec89fa-windows-x86_64/README
x3f_tools-4ec89fa-windows-x86_64/doc/readme.txt
x3f_tools-4ec89fa-windows-x86_64/doc/copyright.txt
x3f_tools-4ec89fa-windows-x86_64/bin/x3f_extract.exe

/bin/sh: 1: zip: not found

make[2]: *** [../dist/x3f_tools-4ec89fa-windows-x86_64.zip] Error 127

make[2]: Leaving directory `/vagrant/src'

make[1]: *** [dist] Error 2

make[1]: Leaving directory `/vagrant'

make: *** [dist-64] Error 2

**Comment by erikrk** [comment]
I suppose you have to add "apt-get install zip" to Vagrantfile.

**Comment by rolkar** [comment]
I do not understand what you are trying to say.

Or are you saying that it is not necessary to describe
how to set up the windows cross compiler because
also zip is missing?

Hmmmmm ... then installing zip should be a part of the description.

**Comment by mmroden** [comment]
I just tested this, and I still get the failure, but only the first time!

../deps/lib/windows-x86_64/opencv/share/OpenCV/3rdparty/lib/libtbb.a(task.cpp.obj):
duplicate section `.rdata$_ZTIN3tbb4taskE[_ZTIN3tbb4taskE]' has different
size

../deps/lib/windows-x86_64/opencv/share/OpenCV/3rdparty/lib/libtbb.a(scheduler.cpp.obj):
duplicate section `.rdata$_ZTIN3tbb4taskE[_ZTIN3tbb4taskE]' has different
size

install  -D -m 755 -s ../bin/windows-x86_64/x3f_extract.exe
../dist/x3f_tools-0.53-10-gcbf8d40-dirty-windows-x86_64/bin/x3f_extract.exe

strip:../dist/x3f_tools-0.53-10-gcbf8d40-dirty-windows-x86_64/bin/stcxmDkW:
Protocol error

install: strip process terminated abnormally

make[2]: ***
[../dist/x3f_tools-0.53-10-gcbf8d40-dirty-windows-x86_64/bin/x3f_extract.exe]
Error 1

make[2]: Leaving directory `/vagrant/src'

make[1]: *** [dist] Error 2

make[1]: Leaving directory `/vagrant'

make: *** [dist-64] Error 2


but running make again yields:


rm -f ../dist/x3f_tools-0.53-10-gcbf8d40-dirty-windows-x86_64.zip

cd ../dist && zip
/vagrant/dist/x3f_tools-0.53-10-gcbf8d40-dirty-windows-x86_64.zip
x3f_tools-0.53-10-gcbf8d40-dirty-windows-x86_64/doc/readme.txt
x3f_tools-0.53-10-gcbf8d40-dirty-windows-x86_64/doc/copyright.txt
x3f_tools-0.53-10-gcbf8d40-dirty-windows-x86_64/bin/x3f_extract.exe

  adding: x3f_tools-0.53-10-gcbf8d40-dirty-windows-x86_64/doc/readme.txt
(deflated 63%)

  adding: x3f_tools-0.53-10-gcbf8d40-dirty-windows-x86_64/doc/copyright.txt
(deflated 51%)

  adding:
x3f_tools-0.53-10-gcbf8d40-dirty-windows-x86_64/bin/x3f_extract.exe
(deflated 72%)

make[2]: Leaving directory `/vagrant/src'

make[1]: Leaving directory `/vagrant'


I might have had some leftovers.  I'll push an updated vagrant file.

**Comment by erikrk** [comment]
I meant exactly what I said and nothing else, i.e. that installation of
the zip package has to be added to Vagrantfile. It has nothing to do
with cross-compilation per se, but it's needed for packaging since tar
and gzip are not available by default on Windows platforms.

Do we really need a dedicated description for setting up
cross-compilation for Windows? It just deals with installing a few apt
packages. The required packages are all listed in Vagrantfile.

**Comment by erikrk** [comment]
As mentioned before, this is a VirtualBox related issue.

https://www.virtualbox.org/ticket/8463

**Comment by mmroden** [comment]
I actually didn't know that about virtualbox-- good catch.  This might be
worth updating the readme; I can do that on the PR I just submitted.

**Comment by erikrk** [comment]
This has been described in Vagrantfile.
https://github.com/Kalpanika/x3f/pull/57
